### ISSUE TITLE
[Bug] Board do not enters the OTA mode 

### ISSUE THREAD

**Issue by Sfinx** [Moddable-OpenSource/Adafruit_nRF52_Bootloader#2]
This patch fixes OTA for me

```
diff --git a/src/boards/boards.h b/src/boards/boards.h
index fd12c64..edc7666 100644
--- a/src/boards/boards.h
+++ b/src/boards/boards.h
@@ -38,11 +38,11 @@
 #endif
 
 #ifndef BUTTON_DFU
-//#define BUTTON_DFU      BUTTON_1
+#define BUTTON_DFU      BUTTON_1^M
 #endif
 
 #ifndef BUTTON_FRESET
-//#define BUTTON_FRESET   BUTTON_2
+#define BUTTON_FRESET   BUTTON_2^M
 #endif
 
 // The primary LED is usually Red but not in all cases.
```

**Comment by mkellner** [comment]
Hello.
We use the Moddable Four button sometimes to wake the device from sleep. If we also use it as the BUTTON_DFU, then waking from sleep will put the device instantly into DFU mode.

So we rely on the reset button being quickly pressed twice in a row. Then the led will flash and the device will be in DFU mode.

**Comment by Sfinx** [comment]
The issue is about OTA not DFU. I do not have M4 and using XIAO Sense. Without this patch it will never enter OTA

**Comment by mkellner** [comment]
Thank you for more information.

I see that the `Adafruit_nRF52_Bootloader/src/boards/moddable_xiao/board.h` file defines the buttons:
```
#define BUTTON_1            3
#define BUTTON_2            6
```

If you add `BUTTON_DFU` and `BUTTON_FRESET` in that file alone, it will not change the functionality for the other platforms.

The device can be put into DFU mode programmatically using the technique shown here [https://www.moddable.com/documentation/devices/nrf52#ble-update-4](https://www.moddable.com/documentation/devices/nrf52#ble-update-4).
